// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5zgPx97GMmMVpNkf4js-35-YjQW02YUE',
    appId: '1:110798518910:web:ddc48e4c6017bad6f2b62f',
    messagingSenderId: '110798518910',
    projectId: 'chat-app-419f8',
    authDomain: 'chat-app-419f8.firebaseapp.com',
    storageBucket: 'chat-app-419f8.appspot.com',
    measurementId: 'G-74VNK5CZ7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-8XFHGadz-JELwGJCX-KNPieiTo84Di8',
    appId: '1:110798518910:android:34b41954476d2a94f2b62f',
    messagingSenderId: '110798518910',
    projectId: 'chat-app-419f8',
    storageBucket: 'chat-app-419f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUl-42r1H45fV9-jaWs6O52OfPbsZ-EkM',
    appId: '1:110798518910:ios:8a42612d5b4015bdf2b62f',
    messagingSenderId: '110798518910',
    projectId: 'chat-app-419f8',
    storageBucket: 'chat-app-419f8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUl-42r1H45fV9-jaWs6O52OfPbsZ-EkM',
    appId: '1:110798518910:ios:cbeb9671547d1e1cf2b62f',
    messagingSenderId: '110798518910',
    projectId: 'chat-app-419f8',
    storageBucket: 'chat-app-419f8.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
